### ISSUE TITLE
Star removing from screen

### ISSUE THREAD

**Issue by Oakheart27** [SciKids/GestureBasedSystem#8]
Star dissapears from boundaries of screen. 
-Implement checks around boarder
-May be related to issue #7

**Comment by SammieJ201** [comment]
Star is bounded to screen with Mathf.Clamp(). 
NOTE: This only works with orthographic cameras, since that's all we've been working with. If we start using perspective camera (doubtful, but just in case), we have to change the MoveStarWithHands method in MoveStarV2.
NOTE 2: Make sure to keep the main camera labeled as "Main Camera".
